site:
  title: DJ Link Ecosystem Analysis
  url: https://djl-analysis.deepsymmetry.org
  start_page: djl-analysis::startup.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: doc
  - url: ./../../crate-digger
    branches: HEAD
    start_path: doc
asciidoc:
  extensions:
  - asciidoctor-mathjax
plugins:
  - path: antora-generic-svg-extension-plugin
    config:
      generator: bytefield-svg
      name: bytefield
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
