site:
  title: DJ Link Ecosystem Analysis
  url: https://djl-analysis.deepsymmetry.org
  start_page: djl-analysis::startup.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: doc
  - url: https://github.com/Deep-Symmetry/crate-digger.git
    branches: HEAD
    start_path: doc
asciidoc:
  extensions:
  - asciidoctor-mathjax
  - "@deepsymmetry/asciidoctor-bytefield"
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
