= Loading Tracks
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:

When running rekordbox, you can tell a player to load a track from the
collection by dragging the track onto the player icon. This is
implemented by a command that tells the player to load the track, and
that command can be used to cause any player to load a track which is
available somewhere on the network (whether in the rekordbox
collection, or in a media slot on another player).

To do that, send a packet like the one shown below to port 50002 on
the player that you want to cause to load the track, with appropriate
values for _D_ (the device number you are posing as), _D~r~_ (the
device from which the track should be loaded), _S~r~_ (the slot from
which the track should be loaded), _T~r~_ (the type of the track), and
_rekordbox_ (the track ID). These are the same values used in
<<vcdj#cdj-status-packet,CDJ status packets>>.

[[load-track-packet]]
.Load Track command packet.
[bytefield]
----
include::example$status_shared.edn[]

(draw-packet-header 0x19)
(draw-boxes [(hex-text 0 2 :bold) (text "D" :math)])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(draw-box (text "D" :math))
(draw-related-boxes (repeat 3 0))
(draw-box (text "D" :math [:sub "r"]))
(draw-box (text "S" :math [:sub "r"]))
(draw-box (text "T" :math [:sub "r"]))
(draw-box 0)
(draw-box (text "rekordbox" :math) {:span 4})
(draw-related-boxes (concat [0 0 0 0x32] (repeat 0x24 0)))
----

Since this packet uses subtype 00, the length sent in _len~r~_ has the
value `0034`, reflecting the number of bytes which follow it.

Assuming the track can be loaded, the player will respond with a
packet whose type indicator (at byte{nbsp}``0a``) has the value `1a`
to acknowledge the command, and will load the specified track.


include::partial$Footer.adoc[]
