= Loading Tracks and Settings
James Elliott <james@deepsymmetry.org>
:stem: latexmath

Rekordbox provides a few mechanisms by which linked players can be
remotely managed. This section explores the packets used.

== Loading Tracks

When running rekordbox, you can tell a player to load a track from the
collection by dragging the track onto the player icon. This is
implemented by a command that tells the player to load the track, and
that command can be used to cause any player to load a track which is
available somewhere on the network (whether in the rekordbox
collection, or in a media slot on another player).

To do that, send a packet like the one shown below to port 50002 on
the player that you want to cause to load the track, with appropriate
values for _D_ (the device number you are posing as), _D~r~_ (the
device from which the track should be loaded), _S~r~_ (the slot from
which the track should be loaded), _T~r~_ (the type of the track), and
_rekordbox_ (the track ID). These are the same values used in
<<vcdj#cdj-status-packet,CDJ status packets>>.

[[load-track-packet]]
.Load Track command packet.
[bytefield]
----
include::example$status_shared.edn[]

(draw-packet-header 0x19)
(draw-boxes [(hex-text 0 2 :bold) (text "D" :math)])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(draw-box (text "D" :math))
(draw-related-boxes (repeat 3 0))
(draw-box (text "D" :math [:sub "r"]))
(draw-box (text "S" :math [:sub "r"]))
(draw-box (text "T" :math [:sub "r"]))
(draw-box 0)
(draw-box (text "rekordbox" :math) {:span 4})
(draw-related-boxes (concat [0 0 0 0x32] (repeat 0x0c 0)))
(draw-box (text "D" :math [:super-digit 0] [:sub-below-digit "d"]))
(draw-related-boxes (repeat 0x17 0))
----

Since this packet uses subtype 00, the length sent in _len~r~_ has the
value `0034`, reflecting the number of bytes which follow it.

stem:[D_d^0] at byte{nbsp}``40`` (__destination_device__, zero-based)
reflects the player number on which the track is supposed to be
loaded. Unlike most device numbers in the protcol, this value numbers
the players starting with 0 (for player number _D_ this has the value
_D - 1_). So for instance when loading a track on player 1,
stem:[D_d^0] will be `00`. Sending this seems not to be required, as
the player will load the track even if this byte does not have the
correct value.

Assuming the track can be loaded, the player will respond with a
packet whose type indicator (at byte{nbsp}``0a``) has the value `1a`
to acknowledge the command, and will load the specified track.

[NOTE]
====
Unfortunately, although the XDJ-XZ is able to load tracks from a
rekordbox collection when rekordbox tells it to, it does not seem to
be able to be remotely instructed to load tracks from its own USBs, or
from other players. The packets that rekordbox sends to achieve this
are slightly different from the one shown above, in that
byte{nbsp}``20`` has the value `01` rather than `02`, and
byte{nbsp}``4b`` has the value `32` rather than `00`. But even sending
packets constructed exactly like that will not cause the XDJ-XZ to
load a track, unless they are coming from rekordbox, and specifying a
track from its own collection.
====

[[loading-settings]]
== Loading Settings

When rekordbox is linked to a player you can also tell it to apply the
My Settings configuration to that player immediately by navigating to
menu:Preferences[CDJ & Devices > My Settings] and scrolling down to
find the section "`Remote Settings using Pro DJ Link`". When you send
the settings, a 116-byte packet like the one shown below is sent to
port 50002 on the target player.

[[load-settings-packet]]
.Load Settings command packet.
[bytefield]
----
include::example$status_shared.edn[]
(defattrs :small (eval-attribute-spec [:math {:font-size 14}]))

(draw-column-headers)
(draw-related-boxes [0x51 0x73 0x70 0x74 0x31 0x57 0x6d 0x4a 0x4f 0x4c (hex-text 0x34 2 :bold)]
                    :bg-green)
(draw-box nil [{:span 5} :box-above])
(draw-box (text "Device Name (padded with " :plain [:hex "00"] ")") [{:span 15} :box-below])
(draw-boxes [(hex-text 2 2 :bold) (text "D" :math) (text "D" :math [:sub "s"])])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(draw-related-boxes [0x12 0x34 0x56 0x78 0x00 0x00 0x00 0x03])
(draw-box (text "OAD" :small))
(draw-box (text "B" :math [:sub "l"]))
(draw-box (text "Q" :math))
(draw-box (text "ACL" :small))

(draw-box (text "L" :math))
(draw-box 0x01)
(draw-box (text "B" :math [:sub "jr"]))
(draw-box (text "I" :math [:sub "jr"]))
(draw-box (text "SF" :small))
(draw-related-boxes (repeat 3 1))
(draw-box (text "B" :math [:sub "ds"]))
(draw-box (text "L" :math [:sub "el"]))
(draw-box (text "Sync" :small))
(draw-box (text "APM" :small))
(draw-box (text "Q" :math [:sub "bv"]))
(draw-box (text "A" :math [:sub "hc"]))
(draw-box (text "C" :math [:sub "hc"]))
(draw-related-boxes (repeat 2 0))

(draw-box (text "L" :math [:sub "n"]))
(draw-related-boxes (repeat 2 0))
(draw-box (text "Time" :small))
(draw-box (text "Jog" :small))
(draw-box (text "AC" :small))
(draw-box (text "MT" :small))
(draw-box (text "R" :math [:sub "t"]))
(draw-box (text "PM" :small))
(draw-related-boxes (repeat 2 0))
(draw-box (text "VSA" :small))
(draw-box (text "JD" :small))
(draw-box (text "B" :math [:sub "pb"]))
(draw-box (text "B" :math [:sub "jl"]))

(draw-related-boxes [0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
                     0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
                     0x00 0x00 0x00 0x00])
----

This is unusual for a port 50002 packet in that byte{nbsp}``1f``
immediately following the name has the value `02` rather than the `01`
we usually see, and there is no subtype byte following it. Instead, we
follow that with _D_ (the device number we are posing as), and _D~s~_
(the device we are sending this packet to, in order to apply the
settings). _len~r~_ has the value `0050`, reflecting the number of
bytes which follow it.

The value _OAD_ at byte{nbsp}``2c`` controls the player's On Air
Display feature. The value `80` turns it off, and `81` turns it on.

The value _B~l~_ at byte{nbsp}``2d`` controls the brightness of the
player's LCD screen. Legal values range from `81` (the least bright)
to `85` (maximum brightness).

The value _Q_ at byte{nbsp}``2e`` controls the player's Quantize mode.
The value `80` turns it off, and `81` turns it on.

The value _ACL_ at byte{nbsp}``2f`` controls the player's Auto Cue
Level, with the following meanings:

.Auto Cue Level values.
[cols=">1m,<11"]
|===
|Value |Meaning

|80 |-36 dB
|81 |-42 dB
|82 |-48 dB
|83 |-54 dB
|84 |-60 dB
|85 |-66 dB
|86 |-72 dB
|87 |-78 dB
|88 |Memory
|===

The value _L_ at byte{nbsp}``30`` sets the Language used in the player
interface, with the following meanings:

.Language values.
[cols=">1m,<11"]
|===
|Value |Meaning

|81 |English
|82 |French
|83 |German
|84 |Italian
|85 |Dutch
|86 |Spanish
|87 |Russian
|88 |Korean
|89 |Simplified Chinese
|8a |Traditional Chinese
|8b |Japanese
|8c |Portuguese
|8d |Swedish
|8e |Czech
|8f |Magyar
|90 |Danish
|91 |Greek
|92 |Turkish
|===

The value _B~jr~_ at byte{nbsp}``32`` controls the brightness of the
player's jog ring. The value `80` turns off jog ring illumination,
`81` illuminates it dimly, and `82` illuminates it brightly.

The value _I~jr~_ at byte{nbsp}``33`` controls the Jog Ring Indicator
feature of the player (I beleve this causes it to flash when a track
is nearing the end). The value `80` turns the indicator off, and `81`
turns it on.


The value _SF_ at byte{nbsp}``34`` controls the player's Slip Flashing
feature. The value `80` turns it off, and `81` turns it on.

The value _B~ds~_ at byte{nbsp}``38`` controls the the brightness of
the player's disc slot illumination. The value `80` turns it off, and
`81` illuminates it dimly, and `82` illuminates it brightly.

The value _L~el~_ at byte{nbsp}``39`` controls the player's Eject/Load
Lock feature. The value `80` unlocks it, and `81` locks it.

The value _Sync_ at byte{nbsp}``3a`` controls the player's Sync
feature. The value `80` turns it off, and `81` turns it on.

The value _APM_ at byte{nbsp}``3b`` controls the player's Auto Play
Mode. The value `80` activates auto play (continue), and `81` chooses
Single Play.

The value _Q~bv~_ at byte{nbsp}``3c`` controls beat value used when
Quantize is in effect. The value `80` quantizes at the full beat
level, `81` quantizes at half beats, `82` at quarter beats, and `83`
at eighth beats.

The value _A~hc~_ at byte{nbsp}``3d`` controls the player's Hot Cue Auto
Load feature. The value `80` turns it off, `81` turns it on, and `82`
allows the rekordbox track-level setting to control whether the hot
cues should be loaded when loading the track.

The value _C~hc~_ at byte{nbsp}``3e`` controls the player's Hot Cue
Color feature. The value `80` turns it off, and `81` turns it on.

The value _L~n~_ at byte{nbsp}``41`` controls the player's Needle
Lock feature. The value `80` unlocks it, and `81` locks it.

The value _Time_ at byte{nbsp}``44`` controls the Time Mode displayed on
the player. The value `80` displays Elapsed time, while `81` displays
Remaining time.

The value _Jog_ at byte{nbsp}``45`` controls the player Jog Mode. The
value `80` selects CDJ mode, while `81` selects Vinyl mode.

The value _AC_ at byte{nbsp}``46`` controls the player's Auto Cue
feature. The value `80` turns it off, and `81` turns it on.

The value _MT_ at byte{nbsp}``47`` controls the player's Master Tempo
feature. The value `80` turns it off, and `81` turns it on.

The value _R~t~_ at byte{nbsp}``48`` controls the player's Tempo
Range. The value `80` selects ±6, 81 selects ±10, 82 selects ±16, and
83 selects Wide.

The value _PM_ at byte{nbsp}``49`` controls the player's Phase Meter
type. The value `80` selects type 1, and `81` selects type 2.

The value _VSA_ at byte{nbsp}``4c`` controls the player's Vinyl Speed
Adjust feature. The value `80` selects Touch & Release, `81` selects
Touch, and `82` selects Release.

The value _JD_ at byte{nbsp}``4d`` controls the player's Jog Display
mode. The value `80` selects Auto, `81` selects Info, `82` selects
Simple, and `83` selects Artwork.

The value _B~pb~_ at byte{nbsp}``4e`` controls the brightness of the
player's performance pads/buttons. Legal values range from `81` (the
least bright) to `84` (maximum brightness).

The value _B~jl~_ at byte{nbsp}``4f`` controls the brightness of the
player's jog wheel LCD screen. Legal values range from `81` (the least
bright) to `85` (maximum brightness).

NOTE: The My Settings preferences page in rekordbox also has a Mixer
section, with a variety of options in it. However, changing these had
no effect on the packet that rekordbox sent, and did not seem to have
eny effect on the mixer section of my XDJ-XZ, either. My best guess is
that these settings might simply not be controllable remotely from
rekordbox yet. If anyone can find evidence otherwise, please open an
https://github.com/Deep-Symmetry/dysentery/issues[issue], or get in
touch on the
https://deep-symmetry.zulipchat.com/join/vek5i5d5f23j6ahbyomv3waf/[dysentery
Zulip stream] to share what you have discovered.
