= Mixer Integration
James Elliott <james@deepsymmetry.org>
:icons: font
:toc:
:experimental:

This section describes a couple of packet types that support the tight
interaction between DJM mixers and CDJs, specifically the “Fader
Start” feature that can start and stop playback in response to
movements of channel faders and the cross-fader, and the “Channels on
Air” feature that allows players to change the color with which their
platter is illuminated depending on whether their output is currently
audible in the mix.

[[fader-start]]
== Fader Start

Thanks to https://github.com/ErikMinekus[@ErikMinekus] we know that we
can cause players to start or stop playing by sending a packet like
the one shown below to port 50001 of the players, with appropriate
command values for _C~1~_ through _C~4~_ telling that player what to
do. A command value of `00` tells the corresponding player to start
playing if it isn’t already, as long as it is positioned at the
current cue point. The command `01` tells that player to stop playing
and return to the cue point, and the value `02` tells the player to
stay in its current state. (It also seems to work to broadcast the
packet on port 50001, which makes sense, since it can be interpreted
individually by each player, so a single packet can be used to affect
the states of all four players if desired.)

[[fader-start-packet]]
.Fader start packet.
[bytefield]
----
include::example$status_shared.edn[]

(draw-packet-header 0x02)
(draw-boxes [(hex-text 0 2 :bold) (text "D" :math)])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(doseq [i (range 1 5)]
  (draw-box (text "C" :math [:sub i])))
----

Since this packet uses subtype 00, the length sent in _len~r~_ has the
value `0004`, reflecting the four bytes which follow it.

[[channels-on-air]]
== Channels on Air

Thanks to https://github.com/jan2000[@jan2000] we know how the mixer
reports which channels are currently on-air, and we can simulate
this feature ourselves when there is no DJM on the network. (If there
is a DJM present, it will quickly reassert its own on-air state for
all the channels.)

The mixer broadcasts a packet like the one shown below to port 50001,
with appropriate flag values for _F~1~_ through _F~4~_ telling each
player whether its channel is on-air. A flag value of `00` tells the
corresponding player it is off the air (silenced, either due to the
cross fader, channel fader, or input source switch for that channel),
while `01` means the player’s channel is on the air.

[[on-air-packet]]
.On Air flags packet.
[bytefield]
----
include::example$status_shared.edn[]

(draw-packet-header 0x03)
(draw-boxes [(hex-text 0 2 :bold) (text "D" :math)])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(doseq [i (range 1 5)]
  (draw-box (text "F" :math [:sub i])))
(draw-related-boxes (repeat 5 0))
----

Since this packet uses subtype 00, the length sent in _len~r~_ has the
value `0009`, reflecting the nine bytes which follow it.

include::partial$Footer.adoc[]
