= Mixer Startup
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:

== Background

The protocol used by Pioneer professional DJ equipment to communicate
and coordinate performances can be monitored to provide useful
information for synchronizing other software, such as light shows and
sequencers. By creating a “virtual CDJ” that sends appropriate packets
to the network, other devices can be induced to send packets
containing even more useful information about their state. This
document details what has been learned so far about the protocol, and
how to accomplish these tasks.

This information was discovered by studying packet captures and with
the help of https://github.com/Deep-Symmetry/dysentery[dysentery], a
bespoke protocol analysis tool written in Clojure. This document was
created in parallel with the development of dysentery to help spread
the knowledge to other developers using other languages.

Once enough had been understood to start interacting in useful ways
with the devices, the
https://github.com/brunchboy/beat-link#beat-link[Beat Link] library
was written to provide a convenient interface for other programs
running in the Java virtual machine. Eventually enough was learned
about the format of the media databases on USB drives and SD cards
inserted in the players to implement
https://github.com/Deep-Symmetry/crate-digger#crate-digger[Crate
Digger], another Java library which parses them, and whose analysis is
part of this documentation site as well.

Other implementations include
https://github.com/EvanPurkhiser/prolink-go[prolink-go] and
https://github.com/flesniak/python-prodj-link[python-prodj-link].

[[mixer-startup]]
== Mixer Startup

When the mixer starts up, after it obtains an IP address (or gives up
on doing that and self-assigns an address), it sends out what look
like a series of packets{empty}footnote:[The packet capture described
in this analysis can be found at
https://github.com/deep-symmetry/dysentery/raw/master/doc/assets/powerup.pcapng]
simply announcing its existence to UDP port 50000 on the broadcast
address of the local network.

These have a data length{empty}footnote:[Values within packets, packet
lengths, and byte offsets are all shown in hexadecimal in `code` font.
Other numbers are in normal body text font and are decimal.] of `25`
bytes, appear roughly every 300 milliseconds, and have the following
content:

.Initial announcement packets from mixer.
[bytefield]
----
include::example$startup_shared.edn[]

(draw-packet-header 0x0a)

(draw-boxes [1 (hex-text 2 2 :bold)])
(draw-box (text "len" [:math] [:sub "p"]) {:span 2})
(draw-box 2)
----

Byte `0a` (inside the green header section) is shown in bold because
its value changes in the different types of packets that devices send,
and can be used to tell them apart.

The byte following the device name (at byte `20`) seems to always have
the value 1 in every kind of packet seen. The next byte is in bold as
well because it seems to indicate the structure of the remainder of
the packet. The value `02` is followed by a two-byte value _len~p~_
that indicates the length of the entire packet (including the
preceding header bytes), and followed by the payload. In the case of
this kind of packet, the length is `0025`, and the payload is the
single-byte value `02`.

After about three of these packets are sent, another series of three
begins. It is not clear what purpose these packets serve, because they
are not yet asserting ownership of any device number; perhaps they are
used when CDJs are powering up as part of the mechanism the mixer can
use to tell them which device number to use based on which network
port they are connected to?

In any case, these three packets have the value `00` at byte `0a`, a
data length of `2c` bytes (reflected in _len~p~_), are again sent to
UDP port 50000 on the local network broadcast address, at roughly 300
millisecond intervals, and have the following content:

.First-stage mixer device number assignment packets.
[bytefield]
----
include::example$startup_shared.edn[]

(draw-packet-header 0)

(draw-boxes [1 (hex-text 2 2 :bold)])
(draw-box (text "len" [:math] [:sub "p"]) {:span 2})
(draw-boxes [(text "N" :math) 2])
(draw-box "MAC address" {:span 6})
----

The value _N_ at byte `24` is `01`, `02`, or `03`, depending on
whether this is the first, second, or third time the packet is sent.

After these comes another series of three numbered packets. These
appear to be claiming the device number for a particular device, as
well as announcing the IP address at which it can be found. They have
a data length and _len~p~_ value of `32` bytes, and are again sent to
UDP port 50000 on the local network broadcast address, at roughly 300
millisecond intervals, with the following content:

.Second-stage mixer device number assignment packets.
[bytefield]
----
include::example$startup_shared.edn[]

(draw-packet-header 2)

(draw-boxes [1 (hex-text 2 2 :bold)])
(draw-box (text "len" [:math] [:sub "p"]) {:span 2})
(draw-box "IP address" {:span 4})
(draw-box "MAC address" {:span 6})
(draw-boxes (map #(text % :math) ["D" "N"]))

(draw-box 2 :box-first)
(draw-box 1 :box-last)
----

I identify these as claiming/identifying the device number because the
value _D_ at byte `2e` is the same as the device number that the mixer
uses to identify itself (`21`) and the same is true for the
corresponding packets seen from my CDJs (they use device numbers `02`
and `03`, as they are connected to those ports/channels on the mixer).

As with the previous series of three packets, the value _N_ at byte
`2f` takes on the values `01`, `02`, and `03` in the three packets.

These are followed by another three packets, perhaps the last stage of
claiming the device number, again at 300 millisecond intervals, to the
same port 50000. These shorter packets have `2a` bytes of data and the
content shown here:

.Final-stage mixer device number assignment packets.
[bytefield]
----
include::example$startup_shared.edn[]

(draw-packet-header 4)

(draw-boxes [1 (hex-text 2 2 :bold)])
(draw-box (text "len" [:math] [:sub "p"]) {:span 2})
(draw-related-boxes [1 2 0 0x26])
(draw-boxes (map #(text % :math) ["D" "N"]))
----

As before the value _D_ at byte `24` is the same as the device number
that the mixer uses to identify itself (`21`) and _N_ at byte `25`
takes on the values `01`, `02`, and `03` in the three packets.

Once those are sent, the mixer seems to settle down and send what
looks like a keep-alive packet to retain presence on the network and
ownership of its device number, at a less frequent interval. These
packets are `36` bytes long, again sent to port 50000 on the local
network broadcast address, roughly every second and a half. They have
the following content:

.Mixer keep-alive packets.
[bytefield]
----
include::example$startup_shared.edn[]

(draw-packet-header 6)

(draw-boxes [1 (hex-text 2 2 :bold)])
(draw-box (text "len" [:math] [:sub "p"]) {:span 2})
(draw-boxes [(text "D" :math) 2])
(draw-box "MAC address" {:span 6})
(draw-box "IP address" {:span 4})

(draw-related-boxes [1 0 0 0 2 0])
----

include::partial$Footer.adoc[]
