= DJ Link Packet Analysis
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:

// Set up support for relative links on GitHub, and give it
// usable icons for admonitions, w00t! Add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[]
:outfilesuffix: .adoc
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::env-github[]

// Render section header anchors in a GitHub-compatible way.
ifndef::env-github[]
:idprefix:
:idseparator: -
endif::env-github[]

The protocol used by Pioneer professional DJ equipment to communicate
and coordinate performances can be monitored to provide useful
information for synchronizing other software, such as light shows and
sequencers. By creating a “virtual CDJ” that sends appropriate packets
to the network, other devices can be induced to send packets
containing even more useful information about their state. This
document details what has been learned so far about the protocol, and
how to accomplish these tasks.

This information was discovered by studying packet captures and with
the help of https://github.com/Deep-Symmetry/dysentery[dysentery], a
bespoke protocol analysis tool written in Clojure. This document was
created in parallel with the development of dysentery to help spread
the knowledge to other developers using other languages.

Once enough had been understood to start interacting in useful ways
with the devices, the
https://github.com/brunchboy/beat-link#beat-link[Beat Link] library
was written to provide a convenient interface for other programs
running in the Java virtual machine. Eventually enough was learned
about the format of the media databases on USB drives and SD cards
inserted in the players to implement
https://github.com/Deep-Symmetry/crate-digger#crate-digger[Crate
Digger], another Java library which parses them, and whose analysis is
part of this documentation site as well.

Other implementations include
https://github.com/EvanPurkhiser/prolink-go[prolink-go] and
https://github.com/flesniak/python-prodj-link[python-prodj-link].

[[mixer-startup]]
== Mixer Startup

When the mixer starts up, after it obtains an IP address (or gives up
on doing that and self-assigns an address), it sends out what look
like a series of packets{empty}footnote:[The packet capture described
in this analysis can be found at
https://github.com/deep-symmetry/dysentery/raw/master/doc/assets/powerup.pcapng]
simply announcing its existence to UDP port 50000 on the broadcast
address of the local network.

These have a data length{empty}footnote:[Values within packets, packet
lengths, and byte offsets are all shown in hexadecimal in `code` font.
Other numbers are in normal body text font and are decimal.] of `25`
bytes, appear roughly every 300 milliseconds, and have the following
content:

.Initial announcement packets from mixer.
[bytefield]
----
include::example$bytefield_setup.edn[]
include::example$mixer_announcement_packet.edn[]
----

Byte `0a` (inside the green header section) is shown in bold because
its value changes in the different types of packets that devices send,
and can be used to tell them apart.

The byte following the device name (at byte `20`) seems to always have
the value 1 in every kind of packet seen. The next byte is in bold as
well because it seems to indicate the structure of the remainder of
the packet. The value `02` is followed by a two-byte value _len~p~_
that indicates the length of the entire packet (including the
preceding header bytes), and followed by the payload. In the case of
this kind of packet, the length is `0025`, and the payload is the
single-byte value `02`.

After about three of these packets are sent, another series of three
begins. It is not clear what purpose these packets serve, because they
are not yet asserting ownership of any device number; perhaps they are
used when CDJs are powering up as part of the mechanism the mixer can
use to tell them which device number to use based on which network
port they are connected to?

In any case, these three packets have the value `00` at byte `0a`, a
data length of `2c` bytes (reflected in _len~p~_), are again sent to
UDP port 50000 on the local network broadcast address, at roughly 300
millisecond intervals, and have the following content:

.First-stage mixer device number assignment packets.
[bytefield]
----
include::example$bytefield_setup.edn[]
include::example$mixer_number_assign_packet_1.edn[]
----


To be continued...

.Cue point response message.
[bytefield]
----
;; Figure 48
include::example$bytefield_setup.edn[]
include::example$cue_point_response.edn[]
----

include::partial$Footer.adoc[]
