name: Build and publish the protocol analysis

on:
  push:
    branches:
      - main

jobs:
  build_analysis:
    name: Build protocol analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v3

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GUIDE_SSH_KEY }}
        known_hosts: 'deepsymmetry.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMKq8T1IXQHNYLgO715YbxTXoVxEsJcha9h1lxyOXpa'

    - name: Cache htmltest results
      uses: actions/cache@v3
      with:
        path: tmp/.htmltest
        key: ${{ runner.os }}-htmltest

    - name: Build and publish protocol analysis
      env:
        GUIDE_SSH_KEY: ${{ secrets.GUIDE_SSH_KEY }}
      run: bash .github/scripts/build_guide.sh
